name: Update Discord Status
on:
  schedule: [{cron: "*/7 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main", "snekOutput"]}

jobs:
  status:
    runs-on: ubuntu-latest
    name: Update Discord Status
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Update Status
        uses: CompeyDev/discord-status-action@0.2.4
        with:
          file: README.md
          id: "594864203102158859"
      - name: Commit and push if there are changes
        env: 
            BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
        run: |-
          git diff
          git config --global user.email $BOT_EMAIL
          git config --global user.name "CoopPlayzzBot"
          git diff --quiet || (git add -u && git commit -m "🚀 Update Discord Status")
          git push               
