name: snek

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-stats-snek.svg
            dist/github-stats-snek-dark.svg?palette=github-dark
      - name: push github-contribution-grid-snake.svg to the output branch
        env: 
            BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
        run: |-
          git config --global user.email $BOT_EMAIL
          git config --global user.name "CoopPlayzzBot"
          git add -u && git commit -m "Update snek"
          git push origin snekOutput
